/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-12-09 15:36:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"HandheldFriendly\" content=\"true\"/>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\"/>\r\n");
      out.write("    <meta name=\"keywords\" content=\"MySportClub, Activities, Climbing, Cycling, Friendly Fire, Manfred Hiller\">\r\n");
      out.write("    <meta name=\"robots\" content=\"index, follow\">\r\n");
      out.write("    <meta name=\"description\" content=\"Search and find famous teams and tournaments.\">\r\n");
      out.write("    <meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\">\r\n");
      out.write("\r\n");
      out.write("    <title>MySportClub</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- ############ import css files ########################################################################################################################### -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/layout.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/print.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ############ import js lib files ######################################################################################################################## -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- ############ import js src files ######################################################################################################################## -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/cookieHandler.js\"></script>\r\n");
      out.write("    <script src=\"./js/main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-myColor\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"home.html\">\r\n");
      out.write("        <i class=\"fa fa-soccer-ball-o\"></i>\r\n");
      out.write("        MySportClub\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- navbar toggler is only shown if page width is small enough (jquery needed) -->\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar\"\r\n");
      out.write("            aria-controls=\"navbar\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!-- standard nav bar for normal desktop sizes -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbar\">\r\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"home.html\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"loginHandler?dispatchto=./clubs/climbing_club.html\">Climbing</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"loginHandler?dispatchto=./clubs/cycling_club.html\">Cycling</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"loginHandler?dispatchto=./clubs/friendlyFire_eSport_club.html\">Friendly Fire</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <!-- guestbook, registry and eMail-->\r\n");
      out.write("        <ul class=\"navbar-nav right\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"./tableGenerator.jsp\">FunHouse</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"guestbook_overview\">Guestbook</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"./account.jsp\">Registry</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"mailto:thisIsAEmail@hotmail.com\">\r\n");
      out.write("                    <i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    Contact\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<main role=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    <div class=\"jumbotron my-jumbotron-sub\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1>Create New Account</h1>\r\n");
      out.write("            <p>\r\n");
      out.write("                * fields are necessary\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- overview/main information -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <form action=\"accountRegistryHandler\"\r\n");
      out.write("              method=\"post\"\r\n");
      out.write("              onsubmit=\"return validateInputs()\" novalidate>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"firstName\">First name *</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"firstName\" id=\"firstName\" placeholder=\"John\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide a valid first name.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"lastName\">Surname *</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"lastName\" id=\"lastName\" placeholder=\"Doe\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide a valid last name.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"address\">Address *</label>\r\n");
      out.write("                    <textarea class=\"md-textarea form-control\" name=\"address\" id=\"address\" rows=\"3\"></textarea>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide a valid address.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"country\">Country *</label>\r\n");
      out.write("                    <select class=\"custom-select\" name=\"country\" id=\"country\">\r\n");
      out.write("                        <option selected value=\"\">Select..</option>\r\n");
      out.write("\r\n");
      out.write("                        <option>Austria</option>\r\n");
      out.write("                        <option>Switzerland</option>\r\n");
      out.write("                        <option>Germany</option>\r\n");
      out.write("                        <option>others</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please select a country.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Gender *</label><br>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"male\" value=\"male\" required>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"male\">Male</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"female\" value=\"female\" required>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"female\">Female</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"diverse\" value=\"diverse\" required>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"diverse\">Divers</label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"gender-feedback\" class=\"invalid-feedback\">Please select a gender.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"userID\">Your User-ID *</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"userID\" id=\"userID\" placeholder=\"john.doe\">\r\n");
      out.write("                <div class=\"invalid-feedback\">Please provide a valid userID.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"email\">E-Mail *</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"john.doe@email.com\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide a valid email.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"mobileNumber\">Mobile Number</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"mobileNumber\" id=\"mobileNumber\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"password\">Password *</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide a valid password.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <label for=\"confirmPassword\">Confirm Password *</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"confirmPassword\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide a valid confirmation password.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"sportCategories\">Sport Categories *</label>\r\n");
      out.write("                <select multiple class=\"form-control\" id=\"sportCategories\" name=\"sportCategory\">\r\n");
      out.write("                    <option>Climbing</option>\r\n");
      out.write("                    <option>Cycling</option>\r\n");
      out.write("                    <option>Friendly Fire</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"invalid-feedback\">Please select a sport category.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\" id=\"user-category-checkboxes\">\r\n");
      out.write("                <label>User Categories *</label><br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"checkbox\" name=\"userCategory\" id=\"athlete\" value=\"athlete\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"athlete\">Athlete</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"checkbox\" name=\"userCategory\" id=\"organizer\"\r\n");
      out.write("                           value=\"organizer\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"organizer\">Organizer</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"checkbox\" name=\"userCategory\" id=\"admin\" value=\"admin\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"admin\">Admin</label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"sportCategories-feedback\" class=\"invalid-feedback\">Please select at least one user category.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"btn my-btn-secondary accountButton\" type=\"reset\">Reset Details</button>\r\n");
      out.write("            <button class=\"btn my-btn-primary accountButton\" type=\"submit\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("    <p>\r\n");
      out.write("        &copy; MySportClub 2021\r\n");
      out.write("        <span class=\"versionNum\">v1.2</span>\r\n");
      out.write("    </p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
